"""added some columns to user

Revision ID: 148e235727e8
Revises: a5039f1bca1c
Create Date: 2024-03-26 08:11:09.538820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '148e235727e8'
down_revision = 'a5039f1bca1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_users')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fav_book', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.String(), nullable=True))
        # batch_op.alter_column(sa.Column('password', nullable=False, new_column_name='_password_hash'))
        batch_op.alter_column('password', nullable=False, new_column_name='_password_hash')
        # batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.create_unique_constraint('email_constraint', ['email'])
        # batch_op.drop_column('password')
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        # batch_op.drop_column('_password_hash')
        # batch_op.alter_column(sa.Column('_password_hash', nullable=False, new_column_name='password'))
        batch_op.alter_column('_password_hash', nullable=False, new_column_name='password')
        batch_op.drop_column('bio')
        batch_op.drop_column('fav_book')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
