"""added user_id to story table and relationship from user to story

Revision ID: fc94d0c5cb28
Revises: f4a0aa52b380
Create Date: 2024-03-27 12:44:06.141714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc94d0c5cb28'
down_revision = 'f4a0aa52b380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('_alembic_tmp_stories')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_foreign_key(batch_op.f('fk_stories_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stories_user_id_users'), type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
